local _, _ = ...
local L = setmetatable({}, { __index = function(t, k) return k end })
ICN2.L = L

-- ── English (Default) ─────────────────────────────────────────────────────────

-- Need names
L["HUNGER"]  = "Hunger"
L["THIRST"]  = "Thirst"
L["FATIGUE"] = "Fatigue"

-- System messages
L["MSG_LOADED"]          = "loaded. Type |cFFFFFF00/icn2|r for options."
L["MSG_MIGRATED_POINTS"] = "Needs migrated to point-based system."
L["MSG_RATES_UPDATED"]   = "Rates updated to v2.5.0 defaults."
L["MSG_RESET"]           = "Needs reset to 100%."
L["MSG_SET_ZERO"]        = "%s set to 0%%."  -- %s = need name (colored)
L["MSG_EAT"]             = "You eat something. Hunger restored."
L["MSG_DRINK"]           = "You drink something. Thirst restored."
L["MSG_REST"]            = "You rest. Fatigue restored."
L["MSG_HUD_ENABLED"]     = "HUD |cFF00FF00enabled|r"
L["MSG_HUD_DISABLED"]    = "HUD |cFFFF0000disabled|r"
L["MSG_HUD_LOCKED"]      = "HUD |cFFFF0000locked|r"
L["MSG_HUD_UNLOCKED"]    = "HUD |cFF00FF00unlocked|r"
L["MSG_COMMANDS"]        = "Commands: |cFFFFFF00/icn2|r [show|eat|drink|rest|reset|starve|dehydrate|exhaust|status|details|hud|lock]"

-- Status / Details output
L["DETAILS_HEADER"]           = "|cFFFFFF00Details|r — "
L["DETAILS_HUNGER_LINE"]      = "|cFF00FF00Hunger|r  %.1f%%  (%.1f / %d pts)  net %+.4f pts/min"
L["DETAILS_THIRST_LINE"]      = "|cFF4499FFThirst|r  %.1f%%  (%.1f / %d pts)  net %+.4f pts/min"
L["DETAILS_FATIGUE_LINE"]     = "|cFFFFDD00Fatigue|r %.1f%%  (%.1f / %d pts)  net %+.4f pts/min  (recovery %+.4f pts/min [%s])"
L["DETAILS_ACTIVE_MOD"]       = "|cFFAAAAAAActive modifiers:|r"
L["DETAILS_NO_MOD"]           = "  |cFF888888None (walking/idle outdoors)|r"
L["DETAILS_ARMOR"]            = "  |cFFCCCCCCArmor:%s (F×%.2f)|r"
L["DETAILS_FAT_RECOVERY"]     = "  |cFFCCCCCCFatigue recovery: %s — sources: %s|r"
L["DETAILS_CROSS_NEED"]       = "  |cFFFF9900Cross-need: %s|r"
L["DETAILS_EATING"]           = "|cFF00FF00Currently eating|r  (tier: %s)"
L["DETAILS_DRINKING"]         = "|cFF4499FFCurrently drinking|r (tier: %s)"
L["DETAILS_WELLFED"]          = "|cFF00FF00Well Fed|r — hunger decay paused (%ds remaining)"
L["STATUS_LINE"]              = "Hunger: |cFF00FF00%.1f%%|r  Thirst: |cFF4499FF%.1f%%|r  Fatigue: |cFFFFDD00%.1f%%|r"

-- Situation modifier labels (for /icn2 details)
L["SIT_INSTANCE"]  = "|cFFFF9900Instance|r (H×%.2f T×%.2f F×%.2f) — aura scanning disabled"
L["SIT_RESTING"]   = "Resting (H×%.2f T×%.2f F×%.2f)"
L["SIT_MOUNTED"]   = "Mounted (H×%.2f T×%.2f F×%.2f)"
L["SIT_FLYING"]    = "Flying (H×%.2f T×%.2f F×%.2f)"
L["SIT_SWIMMING"]  = "Swimming (H×%.2f T×%.2f F×%.2f)"
L["SIT_COMBAT"]    = "Combat (H×%.2f T×%.2f F×%.2f)"
L["SIT_INDOORS"]   = "Indoors (H×%.2f T×%.2f F×%.2f)"
L["SIT_RACE"]      = "Race:%s (H×%.2f T×%.2f F×%.2f)"
L["SIT_CLASS"]     = "Class:%s (H×%.2f T×%.2f F×%.2f)"

-- Preset label (for /icn2 details)
L["PRESET_CUSTOM"]  = "Custom — H×%.2f  T×%.2f  F×%.2f"
L["PRESET_NAMED"]   = "%s (global ×%.2f — slider display %d on 0–%d scale)"

-- Fatigue recovery sources
L["SRC_RESTED_AREA"]    = "rested area"
L["SRC_CAMPFIRE"]       = "campfire"
L["SRC_HOUSING"]        = "housing"
L["SRC_SITTING"]        = "sitting"
L["SRC_EAT_DRINK"]      = "eating/drinking"

-- FoodDrink messages
L["FOOD_BONUS_MSG"]       = "%s completion bonus! (+%.0f pts — %s tier)"
L["FOOD_BONUS_HUNGER"]    = "|cFF00FF00Hunger|r"
L["FOOD_BONUS_THIRST"]    = "|cFF4499FFThirst|r"
L["FOOD_BONUS_BOTH"]      = "|cFF00FF00Hunger|r & |cFF4499FFThirst|r"
L["WELLFED_MSG"]          = "|cFF00FF00Well Fed!|r Hunger decay paused for %d min."

-- HUD tooltip
L["TOOLTIP_TITLE"]   = "|cFFFF6600ICN2 - Character Needs|r"
L["TOOLTIP_HUNGER"]  = "Hunger:  %.1f%%"
L["TOOLTIP_THIRST"]  = "Thirst:  %.1f%%"
L["TOOLTIP_FATIGUE"] = "Fatigue: %.1f%%"
L["TOOLTIP_HINT"]    = "|cFFAAAAAA/icn2 show|r"
L["HUD_TITLE"]       = "Character Needs"

-- Options panel — title
L["OPT_TITLE"] = "|cFFFF6600ICN2|r – Character Needs  |cFF888888v2.5.0|r"

-- Options — tab labels
L["TAB_GENERAL"] = "General"
L["TAB_DECAY"]   = "Decay & rates"

-- Options — section headers
L["OPT_SEC_HUD"]            = "HUD"
L["OPT_SEC_THEME"]          = "Theme:"
L["OPT_SEC_LABEL_MODE"]     = "Bar label:"
L["OPT_SEC_IMMERSION"]      = "Immersion"
L["OPT_SEC_EMOTES"]         = "Emotes"
L["OPT_SEC_MANUAL_RESTORE"] = "Manual restore"
L["OPT_SEC_MANUAL_DEPLETE"] = "Manual deplete"
L["OPT_SEC_DECAY_PRESET"]   = "Decay preset"
L["OPT_SEC_BIAS"]           = "Per-need decay bias"

-- Options — checkboxes / sliders
L["OPT_HUD_ENABLED"]       = "Enable HUD"
L["OPT_HUD_LOCKED"]        = "Lock HUD position"
L["OPT_FREEZE_OFFLINE"]    = "Freeze needs while offline  |cFF888888(no offline decay)|r"
L["OPT_EMOTES_ENABLED"]    = "Enable automatic emotes"
L["OPT_OPACITY"]           = "Opacity"
L["OPT_SCALE"]             = "Scale"
L["OPT_BAR_LENGTH"]        = "Bar length"
L["OPT_EMOTE_CHANCE"]      = "Emote chance"
L["OPT_EMOTE_INTERVAL"]    = "Min interval (sec)"
L["OPT_IMMERSIVE"]         = "Immersive Mode (Hide at 100%)"
L["OPT_DECAY_PRESET"]      = "Global Decay Preset"
L["OPT_HUD_SCALE"]         = "HUD Bar Scale"

-- Options — buttons
L["BTN_EAT"]       = "|cFF00FF00Eat|r"
L["BTN_DRINK"]     = "|cFF4499FFDrink|r"
L["BTN_REST"]      = "|cFFFFDD00Rest|r"
L["BTN_RESET"]     = "|cFFFF4444Reset|r"
L["BTN_STARVE"]    = "|cFFFF4444Starve|r"
L["BTN_DEHYDRATE"] = "|cFFFF4444Dehydrate|r"
L["BTN_EXHAUST"]   = "|cFFFF4444Exhaust|r"

-- Options — dropdown: label modes
L["LABEL_NONE"]       = "None"
L["LABEL_PERCENTAGE"] = "Percentage"
L["LABEL_NUMBER"]     = "Number"
L["LABEL_BOTH"]       = "Both"

-- Options — informational text
L["OPT_FOOD_AUTO"]  = "|cFF888888Food/drink buffs are detected automatically.|r"
L["DESC_DECAY"]     = "Choose a preset for global decay speed, or Custom to tune each need."
L["DESC_DECAY_LONG"] = "|cFFCCCCCCChoose a preset for global decay speed, or |cFFFFCC00Custom|r to tune each need.|r\n|cFF888888Custom multiplier vs Medium (1×): |cFFFFFFFF0|r = no passive decay; |cFFFFFFFF%d|r = 10× Fast. Sliders are read-only unless Custom.|r"

-- Options — decay bias slider label
L["BIAS_LABEL"]          = "%s: %d  (×%.2f vs Medium base)"
L["BIAS_LABEL_READONLY"] = "%s: %d  (×%.2f vs Medium base)  |cFF888888(preset)|r"

-- ── Portuguese (ptBR) ─────────────────────────────────────────────────────────
if GetLocale() == "ptBR" then
    L["HUNGER"]  = "Fome"
    L["THIRST"]  = "Sede"
    L["FATIGUE"] = "Fadiga"

    L["MSG_LOADED"]          = "carregado. Digite |cFFFFFF00/icn2|r para opções."
    L["MSG_MIGRATED_POINTS"] = "Necessidades migradas para o sistema de pontos."
    L["MSG_RATES_UPDATED"]   = "Taxas atualizadas para os padrões v2.5.0."
    L["MSG_RESET"]           = "Necessidades restauradas para 100%."
    L["MSG_SET_ZERO"]        = "%s definido para 0%%."
    L["MSG_EAT"]             = "Você come algo. Fome restaurada."
    L["MSG_DRINK"]           = "Você bebe algo. Sede restaurada."
    L["MSG_REST"]            = "Você descansa. Fadiga restaurada."
    L["MSG_HUD_ENABLED"]     = "HUD |cFF00FF00ativado|r"
    L["MSG_HUD_DISABLED"]    = "HUD |cFFFF0000desativado|r"
    L["MSG_HUD_LOCKED"]      = "HUD |cFFFF0000bloqueado|r"
    L["MSG_HUD_UNLOCKED"]    = "HUD |cFF00FF00desbloqueado|r"
    L["MSG_COMMANDS"]        = "Comandos: |cFFFFFF00/icn2|r [show|eat|drink|rest|reset|starve|dehydrate|exhaust|status|details|hud|lock]"

    L["DETAILS_ACTIVE_MOD"]   = "|cFFAAAAAAModificadores ativos:|r"
    L["DETAILS_NO_MOD"]       = "  |cFF888888Nenhum (caminhando/ocioso ao ar livre)|r"
    L["DETAILS_EATING"]       = "|cFF00FF00Comendo|r  (nível: %s)"
    L["DETAILS_DRINKING"]     = "|cFF4499FFBebendo|r (nível: %s)"
    L["DETAILS_WELLFED"]      = "|cFF00FF00Bem Alimentado|r — decaimento de fome pausado (%ds restantes)"
    L["STATUS_LINE"]          = "Fome: |cFF00FF00%.1f%%|r  Sede: |cFF4499FF%.1f%%|r  Fadiga: |cFFFFDD00%.1f%%|r"

    L["SIT_INSTANCE"]  = "|cFFFF9900Instância|r (H×%.2f T×%.2f F×%.2f) — varredura de aura desativada"
    L["SIT_RESTING"]   = "Descansando (H×%.2f T×%.2f F×%.2f)"
    L["SIT_MOUNTED"]   = "Montado (H×%.2f T×%.2f F×%.2f)"
    L["SIT_FLYING"]    = "Voando (H×%.2f T×%.2f F×%.2f)"
    L["SIT_SWIMMING"]  = "Nadando (H×%.2f T×%.2f F×%.2f)"
    L["SIT_COMBAT"]    = "Combate (H×%.2f T×%.2f F×%.2f)"
    L["SIT_INDOORS"]   = "Interior (H×%.2f T×%.2f F×%.2f)"

    L["FOOD_BONUS_HUNGER"]    = "|cFF00FF00Fome|r"
    L["FOOD_BONUS_THIRST"]    = "|cFF4499FFSede|r"
    L["FOOD_BONUS_BOTH"]      = "|cFF00FF00Fome|r & |cFF4499FFSede|r"
    L["FOOD_BONUS_MSG"]       = "Bônus de conclusão de %s! (+%.0f pts — nível %s)"
    L["WELLFED_MSG"]          = "|cFF00FF00Bem Alimentado!|r Decaimento de fome pausado por %d min."

    L["TOOLTIP_TITLE"]   = "|cFFFF6600ICN2 - Necessidades do Personagem|r"
    L["TOOLTIP_HUNGER"]  = "Fome:   %.1f%%"
    L["TOOLTIP_THIRST"]  = "Sede:   %.1f%%"
    L["TOOLTIP_FATIGUE"] = "Fadiga: %.1f%%"
    L["HUD_TITLE"]       = "Necessidades do Personagem"

    L["OPT_TITLE"]             = "|cFFFF6600ICN2|r – Necessidades do Personagem  |cFF888888v2.5.0|r"
    L["TAB_GENERAL"]           = "Geral"
    L["TAB_DECAY"]             = "Decaimento"
    L["OPT_SEC_HUD"]           = "HUD"
    L["OPT_SEC_IMMERSION"]     = "Imersão"
    L["OPT_SEC_EMOTES"]        = "Emotes"
    L["OPT_SEC_MANUAL_RESTORE"]= "Restaurar manualmente"
    L["OPT_SEC_MANUAL_DEPLETE"]= "Esvaziar manualmente"
    L["OPT_SEC_DECAY_PRESET"]  = "Predefinição de decaimento"
    L["OPT_SEC_BIAS"]          = "Viés de decaimento por necessidade"

    L["OPT_HUD_ENABLED"]    = "Habilitar HUD"
    L["OPT_HUD_LOCKED"]     = "Travar posição do HUD"
    L["OPT_FREEZE_OFFLINE"] = "Congelar necessidades offline  |cFF888888(sem decaimento offline)|r"
    L["OPT_EMOTES_ENABLED"] = "Habilitar Emotes Automáticos"
    L["OPT_OPACITY"]        = "Opacidade"
    L["OPT_SCALE"]          = "Escala"
    L["OPT_BAR_LENGTH"]     = "Comprimento da barra"
    L["OPT_EMOTE_CHANCE"]   = "Chance de emote"
    L["OPT_EMOTE_INTERVAL"] = "Intervalo mínimo (seg)"
    L["OPT_IMMERSIVE"]      = "Modo Imersivo (Esconder em 100%)"
    L["OPT_DECAY_PRESET"]   = "Predefinição de Decaimento"
    L["OPT_HUD_SCALE"]      = "Escala da Barra"

    L["BTN_EAT"]       = "|cFF00FF00Comer|r"
    L["BTN_DRINK"]     = "|cFF4499FFBeber|r"
    L["BTN_REST"]      = "|cFFFFDD00Descansar|r"
    L["BTN_RESET"]     = "|cFFFF4444Resetar|r"
    L["BTN_STARVE"]    = "|cFFFF4444Faminto|r"
    L["BTN_DEHYDRATE"] = "|cFFFF4444Desidratado|r"
    L["BTN_EXHAUST"]   = "|cFFFF4444Exausto|r"

    L["LABEL_NONE"]       = "Nenhum"
    L["LABEL_PERCENTAGE"] = "Porcentagem"
    L["LABEL_NUMBER"]     = "Número"
    L["LABEL_BOTH"]       = "Ambos"

    L["OPT_FOOD_AUTO"]   = "|cFF888888Buffs de comida/bebida são detectados automaticamente.|r"
    L["DESC_DECAY"]      = "Escolha a velocidade de decaimento global ou use Customizado para ajustar cada um."
    L["DESC_DECAY_LONG"] = "|cFFCCCCCCEscolha uma predefinição ou |cFFFFCC00Customizado|r para ajustar cada necessidade.|r\n|cFF888888Multiplicador vs Médio (1×): |cFFFFFFFF0|r = sem decaimento; |cFFFFFFFF%d|r = 10× Rápido. Controles somente leitura a menos que seja Customizado.|r"

    L["SRC_RESTED_AREA"] = "área de descanso"
    L["SRC_CAMPFIRE"]    = "fogueira"
    L["SRC_HOUSING"]     = "moradia"
    L["SRC_SITTING"]     = "sentado"
    L["SRC_EAT_DRINK"]   = "comendo/bebendo"

    L["DETAILS_HEADER"]       = "|cFFFFFF00Detalhes|r — "
    L["DETAILS_HUNGER_LINE"]  = "|cFF00FF00Fome|r  %.1f%%  (%.1f / %d pts)  líquido %+.4f pts/min"
    L["DETAILS_THIRST_LINE"]  = "|cFF4499FFSede|r  %.1f%%  (%.1f / %d pts)  líquido %+.4f pts/min"
    L["DETAILS_FATIGUE_LINE"] = "|cFFFFDD00Fadiga|r %.1f%%  (%.1f / %d pts)  líquido %+.4f pts/min  (recuperação %+.4f pts/min [%s])"
    L["DETAILS_ARMOR"]        = "  |cFFCCCCCCArmadura:%s (F×%.2f)|r"
    L["DETAILS_FAT_RECOVERY"] = "  |cFFCCCCCCRecuperação de fadiga: %s — fontes: %s|r"
    L["DETAILS_CROSS_NEED"]   = "  |cFFFF9900Necessidade cruzada: %s|r"
    L["SIT_RACE"]             = "Raça:%s (H×%.2f T×%.2f F×%.2f)"
    L["SIT_CLASS"]            = "Classe:%s (H×%.2f T×%.2f F×%.2f)"
    L["PRESET_CUSTOM"]        = "Customizado — H×%.2f  T×%.2f  F×%.2f"
    L["PRESET_NAMED"]         = "%s (global ×%.2f — exibição do controle %d na escala 0–%d)"
    L["TOOLTIP_HINT"]         = "|cFFAAAAAA/icn2 show|r"
    L["OPT_SEC_THEME"]        = "Tema:"
    L["OPT_SEC_LABEL_MODE"]   = "Rótulo da barra:"
    L["BIAS_LABEL"]           = "%s: %d  (×%.2f vs base Média)"
    L["BIAS_LABEL_READONLY"]  = "%s: %d  (×%.2f vs base Média)  |cFF888888(predefinição)|r"
end

-- ── Spanish (esES / esMX) ─────────────────────────────────────────────────────
if GetLocale() == "esES" or GetLocale() == "esMX" then
    L["HUNGER"]  = "Hambre"
    L["THIRST"]  = "Sed"
    L["FATIGUE"] = "Fatiga"

    L["MSG_LOADED"]          = "cargado. Escribe |cFFFFFF00/icn2|r para opciones."
    L["MSG_MIGRATED_POINTS"] = "Necesidades migradas al sistema de puntos."
    L["MSG_RATES_UPDATED"]   = "Tasas actualizadas a los valores predeterminados v2.5.0."
    L["MSG_RESET"]           = "Necesidades restablecidas al 100%."
    L["MSG_SET_ZERO"]        = "%s establecido en 0%%."
    L["MSG_EAT"]             = "Comes algo. Hambre restaurada."
    L["MSG_DRINK"]           = "Bebes algo. Sed restaurada."
    L["MSG_REST"]            = "Descansas. Fatiga restaurada."
    L["MSG_HUD_ENABLED"]     = "HUD |cFF00FF00activado|r"
    L["MSG_HUD_DISABLED"]    = "HUD |cFFFF0000desactivado|r"
    L["MSG_HUD_LOCKED"]      = "HUD |cFFFF0000bloqueado|r"
    L["MSG_HUD_UNLOCKED"]    = "HUD |cFF00FF00desbloqueado|r"
    L["MSG_COMMANDS"]        = "Comandos: |cFFFFFF00/icn2|r [show|eat|drink|rest|reset|starve|dehydrate|exhaust|status|details|hud|lock]"

    L["DETAILS_ACTIVE_MOD"]   = "|cFFAAAAAAModificadores activos:|r"
    L["DETAILS_NO_MOD"]       = "  |cFF888888Ninguno (caminando/inactivo al aire libre)|r"
    L["DETAILS_EATING"]       = "|cFF00FF00Comiendo|r  (nivel: %s)"
    L["DETAILS_DRINKING"]     = "|cFF4499FFBebiendo|r (nivel: %s)"
    L["DETAILS_WELLFED"]      = "|cFF00FF00Bien alimentado|r — decaimiento de hambre pausado (%ds restantes)"
    L["STATUS_LINE"]          = "Hambre: |cFF00FF00%.1f%%|r  Sed: |cFF4499FF%.1f%%|r  Fatiga: |cFFFFDD00%.1f%%|r"

    L["SIT_INSTANCE"]  = "|cFFFF9900Instancia|r (H×%.2f T×%.2f F×%.2f) — escaneo de auras desactivado"
    L["SIT_RESTING"]   = "Descansando (H×%.2f T×%.2f F×%.2f)"
    L["SIT_MOUNTED"]   = "Montado (H×%.2f T×%.2f F×%.2f)"
    L["SIT_FLYING"]    = "Volando (H×%.2f T×%.2f F×%.2f)"
    L["SIT_SWIMMING"]  = "Nadando (H×%.2f T×%.2f F×%.2f)"
    L["SIT_COMBAT"]    = "Combate (H×%.2f T×%.2f F×%.2f)"
    L["SIT_INDOORS"]   = "Interior (H×%.2f T×%.2f F×%.2f)"

    L["FOOD_BONUS_HUNGER"]    = "|cFF00FF00Hambre|r"
    L["FOOD_BONUS_THIRST"]    = "|cFF4499FFSed|r"
    L["FOOD_BONUS_BOTH"]      = "|cFF00FF00Hambre|r & |cFF4499FFSed|r"
    L["FOOD_BONUS_MSG"]       = "¡Bonificación de finalización de %s! (+%.0f pts — nivel %s)"
    L["WELLFED_MSG"]          = "|cFF00FF00¡Bien alimentado!|r Decaimiento de hambre pausado por %d min."

    L["TOOLTIP_TITLE"]   = "|cFFFF6600ICN2 - Necesidades del Personaje|r"
    L["TOOLTIP_HUNGER"]  = "Hambre:  %.1f%%"
    L["TOOLTIP_THIRST"]  = "Sed:     %.1f%%"
    L["TOOLTIP_FATIGUE"] = "Fatiga:  %.1f%%"
    L["HUD_TITLE"]       = "Necesidades del Personaje"

    L["OPT_TITLE"]             = "|cFFFF6600ICN2|r – Necesidades del Personaje  |cFF888888v2.5.0|r"
    L["TAB_GENERAL"]           = "General"
    L["TAB_DECAY"]             = "Decaimiento"
    L["OPT_SEC_HUD"]           = "HUD"
    L["OPT_SEC_IMMERSION"]     = "Inmersión"
    L["OPT_SEC_EMOTES"]        = "Emotes"
    L["OPT_SEC_MANUAL_RESTORE"]= "Restaurar manualmente"
    L["OPT_SEC_MANUAL_DEPLETE"]= "Agotar manualmente"
    L["OPT_SEC_DECAY_PRESET"]  = "Ajuste de desgaste"
    L["OPT_SEC_BIAS"]          = "Sesgo de desgaste por necesidad"

    L["OPT_HUD_ENABLED"]    = "Activar HUD"
    L["OPT_HUD_LOCKED"]     = "Bloquear posición del HUD"
    L["OPT_FREEZE_OFFLINE"] = "Congelar necesidades offline  |cFF888888(sin decaimiento offline)|r"
    L["OPT_EMOTES_ENABLED"] = "Activar emotos automáticos"
    L["OPT_OPACITY"]        = "Opacidad"
    L["OPT_SCALE"]          = "Escala"
    L["OPT_BAR_LENGTH"]     = "Longitud de barra"
    L["OPT_EMOTE_CHANCE"]   = "Probabilidad de emote"
    L["OPT_EMOTE_INTERVAL"] = "Intervalo mínimo (seg)"
    L["OPT_IMMERSIVE"]      = "Modo inmersivo (Ocultar al 100%)"
    L["OPT_DECAY_PRESET"]   = "Preajuste de desgaste"
    L["OPT_HUD_SCALE"]      = "Escala de la barra"

    L["BTN_EAT"]       = "|cFF00FF00Comer|r"
    L["BTN_DRINK"]     = "|cFF4499FFBeber|r"
    L["BTN_REST"]      = "|cFFFFDD00Descansar|r"
    L["BTN_RESET"]     = "|cFFFF4444Restablecer|r"
    L["BTN_STARVE"]    = "|cFFFF4444Hambrear|r"
    L["BTN_DEHYDRATE"] = "|cFFFF4444Deshidratar|r"
    L["BTN_EXHAUST"]   = "|cFFFF4444Agotar|r"

    L["LABEL_NONE"]       = "Ninguno"
    L["LABEL_PERCENTAGE"] = "Porcentaje"
    L["LABEL_NUMBER"]     = "Número"
    L["LABEL_BOTH"]       = "Ambos"

    L["OPT_FOOD_AUTO"]   = "|cFF888888Los buffs de comida/bebida se detectan automáticamente.|r"
    L["DESC_DECAY"]      = "Elige una velocidad de desgaste global o usa Personalizado para ajustar cada necesidad."
    L["DESC_DECAY_LONG"] = "|cFFCCCCCCElige un ajuste preestablecido o |cFFFFCC00Personalizado|r para ajustar cada necesidad.|r\n|cFF888888Multiplicador vs Medio (1×): |cFFFFFFFF0|r = sin decaimiento; |cFFFFFFFF%d|r = 10× Rápido. Controles de solo lectura a menos que sea Personalizado.|r"

    L["SRC_RESTED_AREA"] = "área de descanso"
    L["SRC_CAMPFIRE"]    = "hoguera"
    L["SRC_HOUSING"]     = "vivienda"
    L["SRC_SITTING"]     = "sentado"
    L["SRC_EAT_DRINK"]   = "comiendo/bebiendo"

    L["DETAILS_HEADER"]       = "|cFFFFFF00Detalles|r — "
    L["DETAILS_HUNGER_LINE"]  = "|cFF00FF00Hambre|r  %.1f%%  (%.1f / %d pts)  neto %+.4f pts/min"
    L["DETAILS_THIRST_LINE"]  = "|cFF4499FFSed|r  %.1f%%  (%.1f / %d pts)  neto %+.4f pts/min"
    L["DETAILS_FATIGUE_LINE"] = "|cFFFFDD00Fatiga|r %.1f%%  (%.1f / %d pts)  neto %+.4f pts/min  (recuperación %+.4f pts/min [%s])"
    L["DETAILS_ARMOR"]        = "  |cFFCCCCCCArmadura:%s (F×%.2f)|r"
    L["DETAILS_FAT_RECOVERY"] = "  |cFFCCCCCCRecuperación de fatiga: %s — fuentes: %s|r"
    L["DETAILS_CROSS_NEED"]   = "  |cFFFF9900Necesidad cruzada: %s|r"
    L["SIT_RACE"]             = "Raza:%s (H×%.2f T×%.2f F×%.2f)"
    L["SIT_CLASS"]            = "Clase:%s (H×%.2f T×%.2f F×%.2f)"
    L["PRESET_CUSTOM"]        = "Personalizado — H×%.2f  T×%.2f  F×%.2f"
    L["PRESET_NAMED"]         = "%s (global ×%.2f — barra %d en escala 0–%d)"
    L["TOOLTIP_HINT"]         = "|cFFAAAAAA/icn2 show|r"
    L["OPT_SEC_THEME"]        = "Tema:"
    L["OPT_SEC_LABEL_MODE"]   = "Etiqueta de barra:"
    L["BIAS_LABEL"]           = "%s: %d  (×%.2f vs base Media)"
    L["BIAS_LABEL_READONLY"]  = "%s: %d  (×%.2f vs base Media)  |cFF888888(preajuste)|r"
end

-- ── French (frFR) ─────────────────────────────────────────────────────────────
if GetLocale() == "frFR" then
    L["HUNGER"]  = "Faim"
    L["THIRST"]  = "Soif"
    L["FATIGUE"] = "Fatigue"

    L["MSG_LOADED"]          = "chargé. Tapez |cFFFFFF00/icn2|r pour les options."
    L["MSG_MIGRATED_POINTS"] = "Besoins migrés vers le système de points."
    L["MSG_RATES_UPDATED"]   = "Taux mis à jour selon les valeurs par défaut v2.5.0."
    L["MSG_RESET"]           = "Besoins rétablis à 100 %."
    L["MSG_SET_ZERO"]        = "%s défini à 0 %%."
    L["MSG_EAT"]             = "Vous mangez quelque chose. Faim restaurée."
    L["MSG_DRINK"]           = "Vous buvez quelque chose. Soif restaurée."
    L["MSG_REST"]            = "Vous vous reposez. Fatigue restaurée."
    L["MSG_HUD_ENABLED"]     = "HUD |cFF00FF00activé|r"
    L["MSG_HUD_DISABLED"]    = "HUD |cFFFF0000désactivé|r"
    L["MSG_HUD_LOCKED"]      = "HUD |cFFFF0000verrouillé|r"
    L["MSG_HUD_UNLOCKED"]    = "HUD |cFF00FF00déverrouillé|r"
    L["MSG_COMMANDS"]        = "Commandes : |cFFFFFF00/icn2|r [show|eat|drink|rest|reset|starve|dehydrate|exhaust|status|details|hud|lock]"

    L["DETAILS_ACTIVE_MOD"]   = "|cFFAAAAAAModificateurs actifs :|r"
    L["DETAILS_NO_MOD"]       = "  |cFF888888Aucun (marche/inactif en extérieur)|r"
    L["DETAILS_EATING"]       = "|cFF00FF00En train de manger|r  (niveau : %s)"
    L["DETAILS_DRINKING"]     = "|cFF4499FFEn train de boire|r (niveau : %s)"
    L["DETAILS_WELLFED"]      = "|cFF00FF00Bien nourri|r — décroissance de la faim suspendue (%ds restantes)"
    L["STATUS_LINE"]          = "Faim : |cFF00FF00%.1f%%|r  Soif : |cFF4499FF%.1f%%|r  Fatigue : |cFFFFDD00%.1f%%|r"

    L["SIT_INSTANCE"]  = "|cFFFF9900Instance|r (H×%.2f T×%.2f F×%.2f) — analyse d'auras désactivée"
    L["SIT_RESTING"]   = "Au repos (H×%.2f T×%.2f F×%.2f)"
    L["SIT_MOUNTED"]   = "Monté (H×%.2f T×%.2f F×%.2f)"
    L["SIT_FLYING"]    = "En vol (H×%.2f T×%.2f F×%.2f)"
    L["SIT_SWIMMING"]  = "En nage (H×%.2f T×%.2f F×%.2f)"
    L["SIT_COMBAT"]    = "Combat (H×%.2f T×%.2f F×%.2f)"
    L["SIT_INDOORS"]   = "Intérieur (H×%.2f T×%.2f F×%.2f)"

    L["FOOD_BONUS_HUNGER"]    = "|cFF00FF00Faim|r"
    L["FOOD_BONUS_THIRST"]    = "|cFF4499FFSoif|r"
    L["FOOD_BONUS_BOTH"]      = "|cFF00FF00Faim|r & |cFF4499FFSoif|r"
    L["FOOD_BONUS_MSG"]       = "Bonus de fin de %s ! (+%.0f pts — niveau %s)"
    L["WELLFED_MSG"]          = "|cFF00FF00Bien nourri !|r Décroissance de la faim suspendue pendant %d min."

    L["TOOLTIP_TITLE"]   = "|cFFFF6600ICN2 - Besoins du Personnage|r"
    L["TOOLTIP_HUNGER"]  = "Faim :    %.1f%%"
    L["TOOLTIP_THIRST"]  = "Soif :    %.1f%%"
    L["TOOLTIP_FATIGUE"] = "Fatigue : %.1f%%"
    L["HUD_TITLE"]       = "Besoins du Personnage"

    L["OPT_TITLE"]             = "|cFFFF6600ICN2|r – Besoins du Personnage  |cFF888888v2.5.0|r"
    L["TAB_GENERAL"]           = "Général"
    L["TAB_DECAY"]             = "Décroissance"
    L["OPT_SEC_HUD"]           = "HUD"
    L["OPT_SEC_IMMERSION"]     = "Immersion"
    L["OPT_SEC_EMOTES"]        = "Emotes"
    L["OPT_SEC_MANUAL_RESTORE"]= "Restaurer manuellement"
    L["OPT_SEC_MANUAL_DEPLETE"]= "Épuiser manuellement"
    L["OPT_SEC_DECAY_PRESET"]  = "Préréglage de décroissance"
    L["OPT_SEC_BIAS"]          = "Biais de décroissance par besoin"

    L["OPT_HUD_ENABLED"]    = "Activer le HUD"
    L["OPT_HUD_LOCKED"]     = "Verrouiller la position du HUD"
    L["OPT_FREEZE_OFFLINE"] = "Geler les besoins hors ligne  |cFF888888(pas de décroissance hors ligne)|r"
    L["OPT_EMOTES_ENABLED"] = "Activer les émotes automatiques"
    L["OPT_OPACITY"]        = "Opacité"
    L["OPT_SCALE"]          = "Échelle"
    L["OPT_BAR_LENGTH"]     = "Longueur de la barre"
    L["OPT_EMOTE_CHANCE"]   = "Chance d'émote"
    L["OPT_EMOTE_INTERVAL"] = "Intervalle minimal (sec)"
    L["OPT_IMMERSIVE"]      = "Mode immersif (Cacher à 100 %)"
    L["OPT_DECAY_PRESET"]   = "Préréglage de décroissance"
    L["OPT_HUD_SCALE"]      = "Échelle de la barre"

    L["BTN_EAT"]       = "|cFF00FF00Manger|r"
    L["BTN_DRINK"]     = "|cFF4499FFBoire|r"
    L["BTN_REST"]      = "|cFFFFDD00Se reposer|r"
    L["BTN_RESET"]     = "|cFFFF4444Réinitialiser|r"
    L["BTN_STARVE"]    = "|cFFFF4444Affamer|r"
    L["BTN_DEHYDRATE"] = "|cFFFF4444Déshydrater|r"
    L["BTN_EXHAUST"]   = "|cFFFF4444Épuiser|r"

    L["LABEL_NONE"]       = "Aucun"
    L["LABEL_PERCENTAGE"] = "Pourcentage"
    L["LABEL_NUMBER"]     = "Nombre"
    L["LABEL_BOTH"]       = "Les deux"

    L["OPT_FOOD_AUTO"]   = "|cFF888888Les buffs nourriture/boisson sont détectés automatiquement.|r"
    L["DESC_DECAY"]      = "Choisissez une vitesse de décroissance globale ou utilisez Personnalisé pour ajuster chaque besoin."
    L["DESC_DECAY_LONG"] = "|cFFCCCCCCChoisissez un préréglage ou |cFFFFCC00Personnalisé|r pour ajuster chaque besoin.|r\n|cFF888888Multiplicateur vs Moyen (1×) : |cFFFFFFFF0|r = pas de décroissance ; |cFFFFFFFF%d|r = 10× Rapide. Contrôles en lecture seule sauf si Personnalisé.|r"

    L["SRC_RESTED_AREA"] = "zone de repos"
    L["SRC_CAMPFIRE"]    = "feu de camp"
    L["SRC_HOUSING"]     = "logement"
    L["SRC_SITTING"]     = "assis"
    L["SRC_EAT_DRINK"]   = "manger/boire"

    L["DETAILS_HEADER"]       = "|cFFFFFF00Détails|r — "
    L["DETAILS_HUNGER_LINE"]  = "|cFF00FF00Faim|r  %.1f%%  (%.1f / %d pts)  net %+.4f pts/min"
    L["DETAILS_THIRST_LINE"]  = "|cFF4499FFSoif|r  %.1f%%  (%.1f / %d pts)  net %+.4f pts/min"
    L["DETAILS_FATIGUE_LINE"] = "|cFFFFDD00Fatigue|r %.1f%%  (%.1f / %d pts)  net %+.4f pts/min  (récupération %+.4f pts/min [%s])"
    L["DETAILS_ARMOR"]        = "  |cFFCCCCCCArmure : %s (F×%.2f)|r"
    L["DETAILS_FAT_RECOVERY"] = "  |cFFCCCCCCRécupération de fatigue : %s — sources : %s|r"
    L["DETAILS_CROSS_NEED"]   = "  |cFFFF9900Besoin croisé : %s|r"
    L["SIT_RACE"]             = "Race : %s (H×%.2f T×%.2f F×%.2f)"
    L["SIT_CLASS"]            = "Classe : %s (H×%.2f T×%.2f F×%.2f)"
    L["PRESET_CUSTOM"]        = "Personnalisé — H×%.2f  T×%.2f  F×%.2f"
    L["PRESET_NAMED"]         = "%s (global ×%.2f — curseur %d sur échelle 0–%d)"
    L["TOOLTIP_HINT"]         = "|cFFAAAAAA/icn2 show|r"
    L["OPT_SEC_THEME"]        = "Thème :"
    L["OPT_SEC_LABEL_MODE"]   = "Texte de la barre :"
    L["BIAS_LABEL"]           = "%s : %d  (×%.2f vs base Moyenne)"
    L["BIAS_LABEL_READONLY"]  = "%s : %d  (×%.2f vs base Moyenne)  |cFF888888(préréglage)|r"
end

-- ── German (deDE) ─────────────────────────────────────────────────────────────
if GetLocale() == "deDE" then
    L["HUNGER"]  = "Hunger"
    L["THIRST"]  = "Durst"
    L["FATIGUE"] = "Erschöpfung"

    L["MSG_LOADED"]          = "geladen. Gib |cFFFFFF00/icn2|r für Optionen ein."
    L["MSG_MIGRATED_POINTS"] = "Bedürfnisse auf punktebasiertes System migriert."
    L["MSG_RATES_UPDATED"]   = "Raten auf v2.5.0-Standardwerte aktualisiert."
    L["MSG_RESET"]           = "Bedürfnisse auf 100 % zurückgesetzt."
    L["MSG_SET_ZERO"]        = "%s auf 0 %% gesetzt."
    L["MSG_EAT"]             = "Du isst etwas. Hunger wiederhergestellt."
    L["MSG_DRINK"]           = "Du trinkst etwas. Durst wiederhergestellt."
    L["MSG_REST"]            = "Du ruhst dich aus. Erschöpfung wiederhergestellt."
    L["MSG_HUD_ENABLED"]     = "HUD |cFF00FF00aktiviert|r"
    L["MSG_HUD_DISABLED"]    = "HUD |cFFFF0000deaktiviert|r"
    L["MSG_HUD_LOCKED"]      = "HUD |cFFFF0000gesperrt|r"
    L["MSG_HUD_UNLOCKED"]    = "HUD |cFF00FF00entsperrt|r"
    L["MSG_COMMANDS"]        = "Befehle: |cFFFFFF00/icn2|r [show|eat|drink|rest|reset|starve|dehydrate|exhaust|status|details|hud|lock]"

    L["DETAILS_ACTIVE_MOD"]   = "|cFFAAAAAAAktive Modifikatoren:|r"
    L["DETAILS_NO_MOD"]       = "  |cFF888888Keine (Gehen/Leerlauf draußen)|r"
    L["DETAILS_EATING"]       = "|cFF00FF00Esse gerade|r  (Stufe: %s)"
    L["DETAILS_DRINKING"]     = "|cFF4499FFTrinke gerade|r (Stufe: %s)"
    L["DETAILS_WELLFED"]      = "|cFF00FF00Gut genährt|r — Hungerverfall pausiert (%ds verbleibend)"
    L["STATUS_LINE"]          = "Hunger: |cFF00FF00%.1f%%|r  Durst: |cFF4499FF%.1f%%|r  Erschöpfung: |cFFFFDD00%.1f%%|r"

    L["SIT_INSTANCE"]  = "|cFFFF9900Instanz|r (H×%.2f T×%.2f F×%.2f) — Aura-Scan deaktiviert"
    L["SIT_RESTING"]   = "Ruhend (H×%.2f T×%.2f F×%.2f)"
    L["SIT_MOUNTED"]   = "Beritten (H×%.2f T×%.2f F×%.2f)"
    L["SIT_FLYING"]    = "Fliegend (H×%.2f T×%.2f F×%.2f)"
    L["SIT_SWIMMING"]  = "Schwimmend (H×%.2f T×%.2f F×%.2f)"
    L["SIT_COMBAT"]    = "Kampf (H×%.2f T×%.2f F×%.2f)"
    L["SIT_INDOORS"]   = "Drinnen (H×%.2f T×%.2f F×%.2f)"

    L["FOOD_BONUS_HUNGER"]    = "|cFF00FF00Hunger|r"
    L["FOOD_BONUS_THIRST"]    = "|cFF4499FFDurst|r"
    L["FOOD_BONUS_BOTH"]      = "|cFF00FF00Hunger|r & |cFF4499FFDurst|r"
    L["FOOD_BONUS_MSG"]       = "%s Abschlussbonus! (+%.0f Pkt. — Stufe %s)"
    L["WELLFED_MSG"]          = "|cFF00FF00Gut genährt!|r Hungerverfall für %d Min. pausiert."

    L["TOOLTIP_TITLE"]   = "|cFFFF6600ICN2 - Charakterbedürfnisse|r"
    L["TOOLTIP_HUNGER"]  = "Hunger:       %.1f%%"
    L["TOOLTIP_THIRST"]  = "Durst:        %.1f%%"
    L["TOOLTIP_FATIGUE"] = "Erschöpfung:  %.1f%%"
    L["HUD_TITLE"]       = "Charakterbedürfnisse"

    L["OPT_TITLE"]             = "|cFFFF6600ICN2|r – Charakterbedürfnisse  |cFF888888v2.5.0|r"
    L["TAB_GENERAL"]           = "Allgemein"
    L["TAB_DECAY"]             = "Verfall & Raten"
    L["OPT_SEC_HUD"]           = "HUD"
    L["OPT_SEC_IMMERSION"]     = "Immersion"
    L["OPT_SEC_EMOTES"]        = "Emotes"
    L["OPT_SEC_MANUAL_RESTORE"]= "Manuell wiederherstellen"
    L["OPT_SEC_MANUAL_DEPLETE"]= "Manuell aufbrauchen"
    L["OPT_SEC_DECAY_PRESET"]  = "Verfallsvorgabe"
    L["OPT_SEC_BIAS"]          = "Verfallsabweichung pro Bedürfnis"

    L["OPT_HUD_ENABLED"]    = "HUD aktivieren"
    L["OPT_HUD_LOCKED"]     = "HUD-Position sperren"
    L["OPT_FREEZE_OFFLINE"] = "Bedürfnisse offline einfrieren  |cFF888888(kein Offline-Verfall)|r"
    L["OPT_EMOTES_ENABLED"] = "Automatische Emotes aktivieren"
    L["OPT_OPACITY"]        = "Deckkraft"
    L["OPT_SCALE"]          = "Skalierung"
    L["OPT_BAR_LENGTH"]     = "Balkenlänge"
    L["OPT_EMOTE_CHANCE"]   = "Emote-Wahrscheinlichkeit"
    L["OPT_EMOTE_INTERVAL"] = "Mindestintervall (Sek.)"
    L["OPT_IMMERSIVE"]      = "Immersiver Modus (Bei 100 % ausblenden)"
    L["OPT_DECAY_PRESET"]   = "Verfallsvorgabe"
    L["OPT_HUD_SCALE"]      = "Leistenskalierung"

    L["BTN_EAT"]       = "|cFF00FF00Essen|r"
    L["BTN_DRINK"]     = "|cFF4499FFTrinken|r"
    L["BTN_REST"]      = "|cFFFFDD00Ausruhen|r"
    L["BTN_RESET"]     = "|cFFFF4444Zurücksetzen|r"
    L["BTN_STARVE"]    = "|cFFFF4444Aushungern|r"
    L["BTN_DEHYDRATE"] = "|cFFFF4444Dehydrieren|r"
    L["BTN_EXHAUST"]   = "|cFFFF4444Erschöpfen|r"

    L["LABEL_NONE"]       = "Keine"
    L["LABEL_PERCENTAGE"] = "Prozent"
    L["LABEL_NUMBER"]     = "Zahl"
    L["LABEL_BOTH"]       = "Beides"

    L["OPT_FOOD_AUTO"]   = "|cFF888888Essen/Trinken-Buffs werden automatisch erkannt.|r"
    L["DESC_DECAY"]      = "Wähle eine globale Verfallsgeschwindigkeit oder nutze Benutzerdefiniert, um jedes Bedürfnis anzupassen."
    L["DESC_DECAY_LONG"] = "|cFFCCCCCCWähle eine Vorgabe oder |cFFFFCC00Benutzerdefiniert|r, um jedes Bedürfnis anzupassen.|r\n|cFF888888Multiplikator vs. Mittel (1×): |cFFFFFFFF0|r = kein Verfall; |cFFFFFFFF%d|r = 10× Schnell. Regler sind schreibgeschützt, außer bei Benutzerdefiniert.|r"

    L["SRC_RESTED_AREA"] = "Ruhegebiet"
    L["SRC_CAMPFIRE"]    = "Lagerfeuer"
    L["SRC_HOUSING"]     = "Unterkunft"
    L["SRC_SITTING"]     = "sitzend"
    L["SRC_EAT_DRINK"]   = "essen/trinken"

    L["DETAILS_HEADER"]       = "|cFFFFFF00Details|r — "
    L["DETAILS_HUNGER_LINE"]  = "|cFF00FF00Hunger|r  %.1f%%  (%.1f / %d Pkt)  netto %+.4f Pkt/Min"
    L["DETAILS_THIRST_LINE"]  = "|cFF4499FFDurst|r  %.1f%%  (%.1f / %d Pkt)  netto %+.4f Pkt/Min"
    L["DETAILS_FATIGUE_LINE"] = "|cFFFFDD00Erschöpfung|r %.1f%%  (%.1f / %d Pkt)  netto %+.4f Pkt/Min  (Erholung %+.4f Pkt/Min [%s])"
    L["DETAILS_ARMOR"]        = "  |cFFCCCCCCRüstung:%s (F×%.2f)|r"
    L["DETAILS_FAT_RECOVERY"] = "  |cFFCCCCCCErschöpfungserholung: %s — Quellen: %s|r"
    L["DETAILS_CROSS_NEED"]   = "  |cFFFF9900Kreuzbedürfnis: %s|r"
    L["SIT_RACE"]             = "Volk:%s (H×%.2f T×%.2f F×%.2f)"
    L["SIT_CLASS"]            = "Klasse:%s (H×%.2f T×%.2f F×%.2f)"
    L["PRESET_CUSTOM"]        = "Benutzerdefiniert — H×%.2f  T×%.2f  F×%.2f"
    L["PRESET_NAMED"]         = "%s (global ×%.2f — Regleranzeige %d auf 0–%d Skala)"
    L["TOOLTIP_HINT"]         = "|cFFAAAAAA/icn2 show|r"
    L["OPT_SEC_THEME"]        = "Design:"
    L["OPT_SEC_LABEL_MODE"]   = "Balkenbeschriftung:"
    L["BIAS_LABEL"]           = "%s: %d  (×%.2f vs Mittlere Basis)"
    L["BIAS_LABEL_READONLY"]  = "%s: %d  (×%.2f vs Mittlere Basis)  |cFF888888(Vorgabe)|r"
end
